apiVersion: v1
kind: Service
metadata:
  name: timeoff
spec:
  type: NodePort
  selector:
    app: timeoff
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30008
    protocol: TCP